services:
  # Nginx service
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs
  # Nodejs service
  nodejs:
    container_name: nodejs
    build:
      context: ./nodejs
    # ports:
    #   - "3000:3000"
  # Flask service
  flask:
    container_name: flask
    build:
      context: ./flask
    # ports:
    #   - "5000:5000"
  kafka:
    container_name: kafka
    image: apache/kafka:3.7.0
    ports:
      - "9092:9092"
