services:
  ########### Nginx service ###########
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - nextjs
  ########### Nextjs service ###########
  nextjs:
    container_name: nextjs
    build:
      context: ./nextjs
    depends_on:
      - flask
    env_file:
      - ./.env
  ########### Flask service ###########
  flask:
    container_name: flask
    env_file:
      - ./.env
    build:
      context: ./flask
  ########### Kafka service ###########
  kafka:
    container_name: kafka
    build:
      context: ./kafka
  ########### Producer service ###########
  producer:
    container_name: producer
    env_file:
      - ./.env
    build:
      context: ./pipeline/producer
    depends_on:
      - kafka
  ########### Consumer service ###########
  consumer:
    container_name: consumer
    env_file:
      - ./.env
    build:
      context: ./pipeline/consumer
    depends_on:
      - kafka
