services:
  ########### Nginx service ###########
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    # image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - express
  ########### Express service ###########
  express:
    container_name: express
    build:
      context: ./express
    depends_on:
      - flask
    # ports:
    #   - "3000:3000"
    env_file:
      - ./.env
  ########### Flask service ###########
  flask:
    container_name: flask
    env_file:
      - ./.env
    build:
      context: ./flask
    ports:
      - "5000:5000"
  ########### Kafka service ###########
  kafka:
    container_name: kafka
    # image: apache/kafka:3.7.0
    build:
      context: ./kafka
    # ports:
    #   - "9092:9092"
  ########### Pipeline service ###########
  pipeline:
    container_name: pipeline
    env_file:
      - ./.env
    build:
      context: ./pipeline
    # ports:
    #   - "5000:5000"
    depends_on:
      - kafka
