services:
  ########### Nginx service ###########
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    # image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - nextjs
  ########### Nextjs service ###########
  nextjs:
    container_name: nextjs
    build:
      context: ./nextjs
    depends_on:
      - flask
    # ports:
    #   - "3000:3000"
    env_file:
      - ./.env
  ########### Flask service ###########
  flask:
    container_name: flask
    env_file:
      - ./.env
    build:
      context: ./flask
  ########### Kafka service ###########
  kafka:
    container_name: kafka
    # image: apache/kafka:3.7.0
    build:
      context: ./kafka
    # ports:
    #   - "9092:9092"
  ########### Pipeline service ###########
  # pipeline:
  #   container_name: pipeline
  #   env_file:
  #     - ./.env
  #   build:
  #     context: ./pipeline
  #   # ports:
  #   #   - "5000:5000"
  #   depends_on:
  #     - kafka
  ########### Producer service ###########
  producer:
    container_name: producer
    env_file:
      - ./.env
    build:
      context: ./pipeline/producer
    depends_on:
      - kafka
  ########### Consumer service ###########
  consumer:
    container_name: consumer
    env_file:
      - ./.env
    build:
      context: ./pipeline/consumer
    depends_on:
      - kafka
