apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment # Unique name of the Deployment within the namespace
  labels:
    app: flask  # For resource management; used to organize and select groups of resources
spec:
  replicas: 3  # Specifies the desired number of Pods
  selector:
    matchLabels:
      app: flask  # Selects Pods with this label for Deployment management
  template:  # Template for creating new Pods
    metadata:
      labels:
        app: flask  # Labels applied to Pods created from this template; must match selector above
    spec:
      containers:
        - name: flask  # Name of the container within the Pod; for identification within the Pod
          image: reistonyt/csc5201-final-project:flask  # The Docker image for the container
          imagePullPolicy: Always
          ports:
            - containerPort: 5000  # The port that the container listens on
          resources:
          envFrom:
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: flask  # The name of the Service
spec:
  type: ClusterIP  # The type of Service; ClusterIP exposes the Service on an internal IP in the cluster
  selector:
    app: flask  # Selects Pods with this label for traffic routing
  ports:
    - protocol: TCP  # The protocol used by the Service (TCP/UDP)
      port: 5000  # The port the Service listens on
      targetPort: 5000  # The port on the Pod to forward traffic to
