# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: kafka-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: do-block-storage
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: reistonyt/csc5201-final-project:kafka
        imagePullPolicy: Always
        resources:
        ports:
        - containerPort: 9092
        - containerPort: 9093
        # volumeMounts:
        # - name: kafka-storage
        #   mountPath: /var/lib/kafka
        # command: ["sleep"]
        # args: ["infinity"]
      # volumes:
      # - name: kafka-storage
      #   persistentVolumeClaim:
      #     claimName: kafka-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
