apiVersion: v1
kind: Service
metadata:
  name: nginx-service # The name of the Service
spec:
  type: LoadBalancer # The type of Service; LoadBalancer exposes the Service externally using a cloud provider's load balancer
  selector:
    app: nginx
  ports:
    - protocol: TCP # The protocol used by the Service (TCP/UDP)
      port: 80 # The port the Service listens on
      targetPort: 80 # The port on the Pod to forward traffic to
