apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: reistonyt/csc5201-final-project:producer
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
          envFrom:
            - secretRef:
                name: app-secrets
